// Code generated by generate.sh, DO NOT EDIT.

package nasMessage

import (
	"bytes"
	"encoding/binary"
	"fmt"

	"github.com/free5gc/nas/nasType"
)

type IdentityResponse struct {
	nasType.ExtendedProtocolDiscriminator
	nasType.SpareHalfOctetAndSecurityHeaderType
	nasType.IdentityResponseMessageIdentity
	nasType.MobileIdentity
}

func NewIdentityResponse(iei uint8) (identityResponse *IdentityResponse) {
	identityResponse = &IdentityResponse{}
	return identityResponse
}

func (a *IdentityResponse) EncodeIdentityResponse(buffer *bytes.Buffer) error {
	if err := binary.Write(buffer, binary.BigEndian, &a.ExtendedProtocolDiscriminator.Octet); err != nil {
		return fmt.Errorf("NAS encode error (IdentityResponse/ExtendedProtocolDiscriminator): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, &a.SpareHalfOctetAndSecurityHeaderType.Octet); err != nil {
		return fmt.Errorf("NAS encode error (IdentityResponse/SpareHalfOctetAndSecurityHeaderType): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, &a.IdentityResponseMessageIdentity.Octet); err != nil {
		return fmt.Errorf("NAS encode error (IdentityResponse/IdentityResponseMessageIdentity): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.MobileIdentity.GetLen()); err != nil {
		return fmt.Errorf("NAS encode error (IdentityResponse/MobileIdentity): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, &a.MobileIdentity.Buffer); err != nil {
		return fmt.Errorf("NAS encode error (IdentityResponse/MobileIdentity): %w", err)
	}
	return nil
}

func (a *IdentityResponse) DecodeIdentityResponse(byteArray *[]byte) error {
	buffer := bytes.NewBuffer(*byteArray)
	if err := binary.Read(buffer, binary.BigEndian, &a.ExtendedProtocolDiscriminator.Octet); err != nil {
		return fmt.Errorf("NAS decode error (IdentityResponse/ExtendedProtocolDiscriminator): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, &a.SpareHalfOctetAndSecurityHeaderType.Octet); err != nil {
		return fmt.Errorf("NAS decode error (IdentityResponse/SpareHalfOctetAndSecurityHeaderType): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, &a.IdentityResponseMessageIdentity.Octet); err != nil {
		return fmt.Errorf("NAS decode error (IdentityResponse/IdentityResponseMessageIdentity): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, &a.MobileIdentity.Len); err != nil {
		return fmt.Errorf("NAS decode error (IdentityResponse/MobileIdentity): %w", err)
	}
	if a.MobileIdentity.Len < 1 {
		return fmt.Errorf("invalid ie length (IdentityResponse/MobileIdentity): %d", a.MobileIdentity.Len)
	}
	a.MobileIdentity.SetLen(a.MobileIdentity.GetLen())
	if err := binary.Read(buffer, binary.BigEndian, &a.MobileIdentity.Buffer); err != nil {
		return fmt.Errorf("NAS decode error (IdentityResponse/MobileIdentity): %w", err)
	}
	for buffer.Len() > 0 {
		var ieiN uint8
		var tmpIeiN uint8
		if err := binary.Read(buffer, binary.BigEndian, &ieiN); err != nil {
			return fmt.Errorf("NAS decode error (IdentityResponse/iei): %w", err)
		}
		// fmt.Println(ieiN)
		if ieiN >= 0x80 {
			tmpIeiN = (ieiN & 0xf0) >> 4
		} else {
			tmpIeiN = ieiN
		}
		// fmt.Println("type", tmpIeiN)
		switch tmpIeiN {
		default:
		}
	}
	return nil
}
